[build]
    command = "sed -i \"s@https://nicetwicede.herokuapp.com@g\" netlify.toml && yarn build"

# API proxying
[[redirects]]
    from = "/api/*"
    to = "https://nicetwicede.herokuapp.com/:splat"
    status = 200
    force = true

# React Router support
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200