
# API proxying
[[redirects]]
    from = "/api/*"
    to = "https://nicetwicede.herokuapp.com/:splat"
    status = 200
    force = true
    headers = {Content-Type = "application/json", x-auth-token = ""}
    
# React Router support
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200