export const GET_SECTION = 'GET_SECTION';
export const GET_SECTIONS = 'GET_SECTIONS';
export const ADD_SECTIONS = 'ADD_SECTIONS';
export const UPDATE_SECTIONS = 'UPDATE_SECTIONS';
export const DELETE_SECTIONS = 'DELETE_SECTIONS';
export const SET_CURRENT_SECTION = 'SET_CURRENT_SECTION';
export const CLEAR_CURRENT_SECTION = 'CLEAR_CURRENT_SECTION';
export const SECTIONS_ERROR = 'SECTIONS_ERROR';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';


