export const SHOW_NAV_SIDEBAR = 'SHOW_NAV_SIDEBAR';
export const SET_NAV_SIDEBAR_SECTION = 'SET_NAV_SIDEBAR_SECTION';
export const SET_NAV_SIDEBAR_ITEM = 'SET_NAV_SIDEBAR_ITEM';
export const SET_NAV_CURRENT = 'SET_NAV_CURRENT';
export const SET_NAV_MOBILE_SIZE = 'SET_NAV_MOBILE_SIZE';
export const SET_NAV_DESKTOP_SIZE = 'SET_NAV_DESKTOP_SIZE';