const ArticleData = [
  {
    id: 1,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 2,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 3,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 4,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 5,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 6,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 7,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 8,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 9,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 10,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 11,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 12,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 13,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 14,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  },
  {
    id: 15,
    section: 'ui-design',
    title: 'The Step-by-Step Guide for Pairing Fonts',
    subtitle: 'A step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny',
    ReadingTime: '7',
    youtube: '',
    spotify: '',
    author: 'Mohammad Mahmoud Agha',
    authorImage: 'https://source.unsplash.com/collection/2',
    date: '05.10.2020',
    HeroImage: 'https://source.unsplash.com/collection/30',
    imageSource: 'Photo by Jon Tyson',
    articleBody: {
      intro: 'intro you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      body: 'body you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.',
      conclusion: 'conclusion you google for how to pair fonts, you’re going to get a lot of awful results. A first-page result recommends pairings no experienced designer would touch with a 10-foot pole. Google Fonts hilariously recommends you pair literally everything with Open Sans and Roboto In the article, I’m going to cut through the crap and give you a step-by-step plan for creating beautiful, professional-quality font pairings. Here’s the skinny (feel free to skip ahead) Determine your brand Brainstorm fonts that subtly convey your brand Choose a body font by legibility Add an additional font to fill out another aspect of the brand Define your new font’s rules of usage Repeat steps 4 and 5 as necessary Let’s get started.'
    },
    likes: '15K',
    views: '125K',
    articleSuggestion: '125K',
    tags: ['Branding', 'Logo']
  }
];


export default ArticleData;