export const GET_MESSAGES = 'GET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';

export const GET_SECTION = 'GET_SECTION';
export const GET_SECTIONS = 'GET_SECTIONS';
export const ADD_SECTIONS = 'ADD_SECTIONS';
export const UPDATE_SECTIONS = 'UPDATE_SECTIONS';
export const DELETE_SECTIONS = 'DELETE_SECTIONS';
export const SET_CURRENT_SECTION = 'SET_CURRENT_SECTION';
export const CLEAR_CURRENT_SECTION = 'CLEAR_CURRENT_SECTION';
export const SECTIONS_ERROR = 'SECTIONS_ERROR';

export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_SECTION_ARTICLES = ' GET_SECTION_ARTICLES';
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_MOST_VISITED_ARTICLES = 'GET_MOST_VISITED_ARTICLES';
export const GET_LATEST_ARTICLES = 'GET_LATEST_ARTICLES';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const UPDATE_NEW_VIEW_ARTICLE = 'UPDATE_NEW_VIEW_ARTICLE';
export const UPDATE_NEW_Like_ARTICLE = 'UPDATE_NEW_Like_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const SET_CURRENT_ARTICLE = 'SET_CURRENT_ARTICLE';
export const CLEAR_CURRENT_ARTICLE = 'CLEAR_CURRENT_ARTICLE';
export const ARTICLE_ERROR = 'ARTICLE_ERROR';

export const GET_IMAGES = 'GET_IMAGES';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const IMAGES_ERROR = 'IMAGES_ERROR';

export const GET_CONTACTS = 'GET_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const CLEAR_CONTACTS = 'CLEAR_CONTACTS';

export const CLEAR_FILTER = 'CLEAR_FILTER';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const UPDATE_USER = 'UPDATE_USER';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const CONTACT_ERROR = 'CONTACT_ERROR';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//nav
export const SHOW_NAV_SIDEBAR = 'SHOW_NAV_SIDEBAR';
export const SET_NAV_SIDEBAR_SECTION = 'SET_NAV_SIDEBAR_SECTION';
export const SET_NAV_SIDEBAR_ITEM = 'SET_NAV_SIDEBAR_ITEM';
export const SET_NAV_CURRENT = 'SET_NAV_CURRENT';

//api add the url /api
export const API = '';

