export const GET_MESSAGES = 'GET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';

export const GET_CONTACTS = 'GET_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const CLEAR_CONTACTS = 'CLEAR_CONTACTS';

export const CLEAR_FILTER = 'CLEAR_FILTER';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const CONTACT_ERROR = 'CONTACT_ERROR';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//nav
export const SHOW_NAV_SIDEBAR = 'SHOW_NAV_SIDEBAR';
export const SET_NAV_SIDEBAR_SECTION = 'SET_NAV_SIDEBAR_SECTION';
export const SET_NAV_SIDEBAR_ITEM = 'SET_NAV_SIDEBAR_ITEM';
export const SET_NAV_CURRENT = 'SET_NAV_CURRENT';