export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_SECTION_ARTICLES = ' GET_SECTION_ARTICLES';
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_MOST_VISITED_ARTICLES = 'GET_MOST_VISITED_ARTICLES';
export const GET_LATEST_ARTICLES = 'GET_LATEST_ARTICLES';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const UPDATE_NEW_VIEW_ARTICLE = 'UPDATE_NEW_VIEW_ARTICLE';
export const UPDATE_NEW_Like_ARTICLE = 'UPDATE_NEW_Like_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const SET_CURRENT_ARTICLE = 'SET_CURRENT_ARTICLE';
export const CLEAR_CURRENT_ARTICLE = 'CLEAR_CURRENT_ARTICLE';
export const ARTICLE_ERROR = 'ARTICLE_ERROR';

